development:
  db:
    uri: "mongodb://localhost/client_dashboard_dev"
  app_secret: 'my app secret'
  useSSL: false
staging:
  db:
    uri: "mongodb://localhost/client_dashboard_staging"
  app_secret: 'my app secret'
  useSSL: false
  analytics_account: ''
production:
  db:
    uri: ''
  app_secret: ''
  useSSL: true
  analytics_account: ''
