development:
  db:
    uri: "mongodb://localhost/client_dashboard_dev"
staging:
  db:
    uri: "mongodb://localhost/client_dashboard_staging"
production:
  db:
    uri: "mongodb://nodejs:nodejs@staff.mongohq.com:10045/app2591449"
